server.port=8080

# Disable database (for deployment)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=